name: Build And Tests

on:
    workflow_call:

jobs:
    build-and-test:
        name: ğŸ—ï¸ Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: â¬‡ï¸ Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: false

            - name: â” Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: â” Set up pnpm
              uses: pnpm/action-setup@v4

            - name: ğŸ“¥ Download deps
              run: pnpm install --frozen-lockfile

            - name: ğŸ” Valid commit message
              if: ${{ github.event_name == 'pull_request' }}
              run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

            - name: ğŸ’„ Prettier
              run: pnpm prettier:check

            - name: ğŸ’… ESLint
              run: pnpm run lint:check

            - name: ğŸ“² Test the builds
              run: pnpm run build

            - name: ğŸ„ Run the tests
              run: pnpm run test
